### ISSUE TITLE
您好，我对您的论文很感兴趣，请问代码未来是否会公开？

### ISSUE THREAD

**Issue by chenjx56** [songkaisong/CADMN#1]
很抱歉打扰您，希望能够拜读您的论文代码！

**Comment by songkaisong** [comment]
论文里已经附上了个人主页，对应的论文有代码下载链接（https://drive.google.com/file/d/17jRY5HGLWu2jO2ZBHDFafg2SLXbbnnB9/view?usp=sharing）。

![image](https://user-images.githubusercontent.com/4067182/189045976-1717f4d5-4895-4042-ad4f-21b33b0f3d44.png)
